apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- portal-configmap.yaml
- portal-deployment.yaml
- portal-service.yaml
- oauth2-proxy-home-deployment.yaml
- oauth2-proxy-home-service.yaml
- oauth2-proxy-admin-deployment.yaml
- oauth2-proxy-admin-service.yaml
- home-ingress.yaml
