apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: home
type: Opaque
stringData:
    home-client-secret: ENC[AES256_GCM,data:MFetWn/D+BbKyobhTnatvO13hMB/rcccVaCn7Yz56QCz1oBlk1NIFQ/JUKz11ZCD+gRsGUbHZiIHAWz66j9jjQ==,iv:aUgXi7BeJ66RZh0e8spjUuQbPxjQUyZHP7KpBtRxpcM=,tag:bKmFCnN0d2/fGMKMNDiUCw==,type:str]
    admin-client-secret: ENC[AES256_GCM,data:Cgeziw9p7aVU92RLsi4etEzICFxV38ynqNeAlxOO4hg2nsc72loTkR9qqlTD/Vkz6Nh8vGO+rE6J1n7Rt8byRQ==,iv:lfQqLm7E1IjkDF2MCTZxodH78d1Y2dYpsbAXfI1lH7k=,tag:oKL91LZ5lnjV7q6+0s0aZg==,type:str]
    home-cookie-secret: ENC[AES256_GCM,data:CNXz0gYZDSO3F9k/NXW0DR1hZipdWAlgsxsc9UUWFUU=,iv:nt5QkI8LEXVXU94B+tlWTE1Mdyyhp3s3dCHu9r+YOjc=,tag:ndNu1gRoV/fJVI2ayA6Ulw==,type:str]
    admin-cookie-secret: ENC[AES256_GCM,data:hk9u63zV8oMvXlWV5RY63TiZaLq0GvPj54YTvtPnax0=,iv:Zf2OCKWjLOklEuv3JKXf+gkTXnEK0HVTxD2tkYNiigY=,tag:haw6GMQiEAO19VOF0hC32A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15437xk7432fpwtrd2gpwcmh7xyzacvp2sy6qr5sq2n3zqah5u9tqw5s539
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycUtuODlNSEIybkdZZERv
            Sk9wYk96VjBFb3BCMkRDV0J5NHcyNHhuQ0JjCkswQkNLajJhUXYxSzhwaHN4ZHMw
            NEtzSlV0OEhoUUxibHJDTkgvSk9vaEEKLS0tIGR5TFgxY2pBaWlHcTAyazlwb2RW
            TVl1RnByTk5hLzBEL012T3QwNDRYNTQKqnWTVVZahRjww1w9nSxikGMzJhjSC1uZ
            2UV8MxNRMzEwDYDM3mRYSnF4p6T9UziJgLuXZy2hH6p9kkHqagr7bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T08:28:15Z"
    mac: ENC[AES256_GCM,data:OhFfnz3a6y57qQTCLllweOfEvD7pybFVZ8CZu5iKtrQQeONS7ydNHgQU45isiPQhcyIltrgJWVS37/8ti4VKSh+wps8V7+zLZixbHpgluSbvk6kc+Z5WKEnkyYCiyEXPt/5WaH1czByeFh/c2QmSrlPyuLv7WyUHJ3S/32MXb44=,iv:J3sWWtDFVPpTQbOZ4t2zYfEhLDdF+kx6aXmwx3HLyT0=,tag:DRdQMIcYqAP0ibc9ajcbQQ==,type:str]
    pgp: []
    encrypted_regex: ^(home-client-secret|admin-client-secret|home-cookie-secret|admin-cookie-secret|client-secret|cookie-secret|secret)$
    version: 3.9.4
