apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: home
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
      volumes:
      - name: html
        configMap:
          name: portal-html
